name: Validate Multiple YAML Files
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install -g yaml-schema-validator

      - name: Validate Car YAML
        run: |
          yaml-schema-validator validate -e -f car.yml -s schemas/schema_car.yml

      - name: Validate Computer YAML
        run: |
          yaml-schema-validator validate -e -f computer.yml -s schemas/schema_computer.yml

      - name: Validate Person YAML
        run: |
          yaml-schema-validator validate -e -f person.yml -s schemas/schema_person.yml

      - name: Validate Schedule YAML
        run: |
          yaml-schema-validator validate -e -f schedule.yml -s schemas/schema_schedule.yml
